knp_snappy:
    process_timeout : 20
    temporary_folder: "C:\\Users\\valen\\Desktop\\snappy"
    pdf:
        enabled:    true
        binary:     "\"C:\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:
            enable-local-file-access : true
            no-outline: true
            page-size: LETTER
            encoding: UTF-8
    image:
        enabled:    true
        binary:     "'C:/wkhtmltopdf/wkhtmltoimage.exe'"
        options:    []
