index:
    path: /
    controller: App\Controller\IndexController::index

accueilSubSkill:
    path: /subskill/{id}
    controller: App\Controller\SubSkillController::getSubSkill

createSkill:
    path: /skill/create
    controller: App\Controller\TestController::createSkill

accueilSkill:
    path: /skill
    controller: App\Controller\TestController::index

createSubSkill:
    path: /subskill/{id}/create
    controller: App\Controller\SubSkillController::createSubSkill
